### ISSUE TITLE
Fallback class defaults to ie-8

### ISSUE THREAD

**Issue by igoratron** [RazvanDH/rs-golden-ratio-grid#2]
Currently the fallback class defaults to `ie-8` which implies that `ie-9` supports flexbox. That is not true. How about the default is `no-flexbox` or something similar?

On a similar note, what's the benefit of supporting flex on IE <Edge at all given their diminishing market shares? (`@supports` hint, hint :))

**Comment by RazvanDH** [comment]
I've addressed this issue here: https://github.com/RazvanDH/rs-golden-ratio-grid/pull/3
